### ISSUE TITLE
Ask application's name when removing app

### ISSUE THREAD

**Issue by dolphinxyz** [stormkit-io/www-stormkit-io#92]
It is common to ask to insert the resource's name whenever a user wants to remove/destroy the resource itself.

Would be great being asked to insert resource name before proceeding with the delete.

Below the same activity of Stormkit VS DigitalOcean

# STORMKIT
![stormkit](https://user-images.githubusercontent.com/30242227/136662493-4aad7ba5-e5a1-423c-92b5-39fb27460821.png)

# DIGITAL OCEAN
![digitalocean](https://user-images.githubusercontent.com/30242227/136662504-543d9066-f7b5-43ae-b98d-ced7f36a633e.png)

**Comment by svedova** [comment]
@dolphinxyz thanks for opening the issue. This repo is only for the landing page and documentation therefore the issue went unnoticed. Luckily though, since this issue is implemented a while ago, I'm going to close this and not move it to https://github.com/stormkit-io/app-stormkit-io.

Here's how the implementation looks like:

<img width="754" alt="image" src="https://user-images.githubusercontent.com/3321893/155664127-fb2085da-4d76-4f7d-890a-3bb4954a01db.png">
