### ISSUE TITLE
Possibility to inject a custom header/cookie on Deploy

### ISSUE THREAD

**Issue by dolphinxyz** [stormkit-io/www-stormkit-io#93]
**Is your feature request related to a problem? Please describe.**
Due to a of lack of experience, I find myself in the situation of being "not sure" if Stormkit is showing the latest version of my code (despite there are many ways to verify it).

**Describe the solution you'd like**
It would be great when I deploy on Stormkit to have the possibility to add a custom header/cookie which can then be simply inspected on the browser inspector, to remove any doubts if Stormkit is showing a certain version.

**Describe alternatives you've considered**
Might there be other ways without involving the browser inspector?

Thanks!

**Comment by svedova** [comment]
@dolphinxyz thanks for opening the issue. This repo is only for the landing page and documentation therefore the issue went unnoticed. Since this issue is implemented a while ago, I'm going to close this and not move it to https://github.com/stormkit-io/app-stormkit-io. 

We inject the `x-sk-version` which is the id of the deployment that is being served.
 
<img width="545" alt="image" src="https://user-images.githubusercontent.com/3321893/155663587-d23bf1b1-ab5b-4629-888c-275ec0edfd82.png">
